config/routes.rb
Rails.application.routes.draw do
  get 'tweets/raw'

  get 'tweets/eu'

  get 'tweet/eu'

  get 'tweet/raw'

  resources :tweets

   root to: 'tweets#index'

    get 'eu' => 'tweets#eu'
    get 'raw' => 'tweets#raw'
    get 'us' => 'tweets#us'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	validates :handle, uniqueness: true

	def self.eu_places
		["Andorra", "Albania", "Austria", "Bosnia-Hercegovina", "Belgium", "Bulgaria", "Belarus", "Switzerland", "Cyprus", "Czech Republic", "Germany", "Denmark", "Estonia", "Spain", "Finland", "Faroe Islands", "France", "Guernsey", "Gibraltar", "Greece", "Croatia", "Hungary", "Ireland", "Isle of Man", "Iceland", "Italy", "Jersey", "Liechtenstein", "Lithuania", "Luxemburg", "Latvia", "Monaco", "Moldova", "Macedonia", "Malta", "Netherlands", "Norway", "Poland", "Portugal", "Romania", "Russia", "Sweden", "Slovenia", "Svalbard", "Slovakia", "San Marino", "West Turkey", "Ukraine", "Vatican City", "Yugoslavia"]
	end

	def self.us_places
		["United States of America", "United States"]
	end

	def self.uk_places
		["United Kingdom"]
	end	

	def self.get_latest

	    $twitter.search("hubs.ly", :result_type => "recent").each do |row|
	        coordlocation = row.place::country
	        description = row.user::description.gsub(",","")
	        biolocation = row.user::location.gsub(",","")	       
	      	if coordlocation.nil?
	        	coordlocation = "coordinates not provided"
	      	end
	      	uk = 'N'
	      	eu = 'N'
	      	us = 'N'

	      	location = Geocoder.search(biolocation)
	      	if location.first
	      		country = location.first.country
	      	else
	      		country = 'NULL'
	      	end

	  		if Tweet.uk_places.include?(country)
	  			uk = "Y"
	  		end
	  		if Tweet.eu_places.include?(country)
	  			eu = "Y"
	  		end
	  		if Tweet.us_places.include?(country)
	  			us = "Y"
	  		end


	      	
	      	
      		unless row.text.include? "RT"
			        t = Tweet.new(
			            tweeturl: "http://twitter.com/#{row.user::screen_name}/status/#{row.id}", 
			            handle: "#{row.user::screen_name}", 
			            name: "#{row.user::name}", 
			            bio: "#{description}", 
			            userlocation: "#{biolocation}", 
			            country: "#{coordlocation}",
			            uk: "#{uk}", 
			            eu: "#{eu}", 
			            us: "#{us}", 
			            )
			        t.save
		    end		    	    	
		end		
	end

	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'will_paginate/array'
  require 'csv'
  def globals
	  @raw = Tweet.all.reorder('id DESC')
	  @tweets = Array.new
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def raw
    @csvtweets = Tweet.where(downloaded: nil)

      respond_to do |format|
        format.html do
          @per_page = params[:per_page] || Tweet.per_page || 20
          if @per_page == "ALL"
            @tweets = Tweet.paginate( :per_page => Tweet.count, :page => params[:page])
          elsif %w(10 20 30 40 50 75 100).any?
            @tweets = Tweet.paginate( :per_page => @per_page, :page => params[:page])
          else
            @tweets = Tweet.paginate( :per_page => 20, :page => params[:page])
          end
        end
        format.csv do
          headers['Content-Disposition'] = "attachment; filename=\"tweet-list\""
          headers['Content-Type'] ||= 'text/csv'
        end
      end
  end

  def eu

    @tweets = Tweet.where(eu: 'Y').reorder('id DESC')
    @csvtweets = Tweet.where(downloaded: nil, eu: 'Y')

    respond_to do |format|
      format.html do
        @per_page = params[:per_page] || Tweet.per_page || 20
        if @per_page == "ALL"
          @eutweets = @tweets.paginate( :per_page => @tweets.count, :page => params[:page])
        elsif %w(10 20 30 40 50 75 100).any?
          @eutweets = @tweets.paginate( :per_page => @per_page, :page => params[:page])
        else
          @eutweets = @tweets.paginate( :per_page => 20, :page => params[:page])
        end
      end
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"tweet-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
    
  end

  def us

    @tweets = Tweet.where(us: 'Y').reorder('id DESC')
     @csvtweets = Tweet.where(downloaded: nil, us: 'Y')

    respond_to do |format|
      format.html do
        @per_page = params[:per_page] || Tweet.per_page || 20
          if @per_page == "ALL"
            @ustweets = @tweets.paginate( :per_page => @tweets.count, :page => params[:page])
          elsif %w(10 20 30 40 50 75 100).any?
            @ustweets = @tweets.paginate( :per_page => @per_page, :page => params[:page])
          else
            @ustweets = @tweets.paginate( :per_page => 20, :page => params[:page])
          end
        end
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"tweet-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def index

    @tweets = Tweet.where(uk: 'Y').reorder('id DESC')
    @csvtweets = Tweet.where(downloaded: nil, uk: 'Y')

    respond_to do |format|
      format.html do
        @per_page = params[:per_page] || Tweet.per_page || 20
        if @per_page == "ALL"
          @uktweets = @tweets.paginate( :per_page => @tweets.count, :page => params[:page])     
         elsif %w(10 20 30 40 50 75 100).any?
          @uktweets = @tweets.paginate( :per_page => @per_page, :page => params[:page])
        else
          @uktweets = @tweets.paginate( :per_page => 20, :page => params[:page])
        end
      end
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"tweet-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweeturl, :handle, :name, :bio, :userlocation, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hub Spot App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<script src="//use.typekit.net/ifw3yzl.js"></script>
	<script>try{Typekit.load();}catch(e){}</script>
</head>
	<body>
		<header>
			<h1>OG HubSpot App</h1>
			<div class="menu">
				<nav>
					<ul>
						<li>
							<a href="/">UK Tweets</a>
						</li>
						<li>
							<a href="/eu">EU Tweets</a>
						</li>
						<li>
							<a href="/us">US Tweets</a>
						</li>
						<li>
							<a href="/raw">All Tweets</a>
						</li>
					</ul>
				</nav>
			</div>
		</header>
		<main>

		<%= yield %>

		</main>
		<script>
			$('.menu').click( function() {
				$('nav').toggleClass('show');
			});
		</script>
	</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweeturl %><br>
    <%= f.text_field :tweeturl %>
  </div>
  <div class="field">
    <%= f.label :handle %><br>
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :userlocation %><br>
    <%= f.text_field :userlocation %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/eu.csv.erb
<%- headers = ['Original Tweet', 'Twitter name', 'Full name', 'Bio', 'Location'] -%>
<%= CSV.generate_line headers %>
<%- @csvtweets.each do |tweet| -%>
  <%= CSV.generate_line([tweet.tweeturl, tweet.handle, tweet.name, tweet.bio, tweet.userlocation]) %>
  <% tweet.update_attribute(:downloaded, 'Y') %>
<%- end -%>

app/views/tweets/eu.html.erb
<p id="notice"><%= notice %></p>

<h1>EU users who use hubs.ly</h1>

<table>
  <thead>
    <tr>
      <th>Original Tweet</th>
      <th>Twitter handle</th>
      <th>Full name</th>
      <th>Bio</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @eutweets.each do |tweet| %>
        <tr>
          <td><a href="<%= tweet.tweeturl %>" target="_blank">Original Tweet</a></td>
          <td><a href="http://twitter.com/<%= tweet.handle %>" target="_blank"><%= tweet.handle %></a></td>
          <td><%= tweet.name %></td>
          <td><%= tweet.bio %></td>
          <td><%= tweet.userlocation %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="pagination">
<div id="pages">
  How many users per page: <%= select_tag :iper_page, options_for_select([10,20,50, 100, "ALL"], params[:per_page].to_i),
         :onchange => "if(this.value){window.location='?per_page='+this.value;}" %></div>
  <%= will_paginate @eutweets %>
</div>

<%= link_to 'Download CSV list', tweets_path(format: :csv), class: "btn" %>

app/views/tweets/index.csv.erb
<%- headers = ['Original Tweet', 'Twitter name', 'Full name', 'Bio', 'Location'] -%>
<%= CSV.generate_line headers %>
<%- @csvtweets.each do |tweet| -%>
  <%= CSV.generate_line([tweet.tweeturl, tweet.handle, tweet.name, tweet.bio, tweet.userlocation]) %>
  <% tweet.update_attribute(:downloaded, 'Y') %>
<%- end -%>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>UK users who use hubs.ly</h1>

<table>
  <thead>
    <tr>
      <th>Original Tweet</th>
      <th>Twitter handle</th>
      <th>Full name</th>
      <th>Bio</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @uktweets.each do |tweet| %>
        <% if tweet.downloaded == nil %>
          <tr>
        <% else %>
          <tr class="downloaded">
        <% end %>
          <td><a href="<%= tweet.tweeturl %>" target="_blank">Original Tweet</a></td>
          <td><a href="http://twitter.com/<%= tweet.handle %>" target="_blank"><%= tweet.handle %></a></td>
          <td><%= tweet.name %></td>
          <td><%= tweet.bio %></td>
          <td><%= tweet.userlocation %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="pagination">
<div id="pages">
  How many users per page: <%= select_tag :iper_page, options_for_select([10,20,50, 100, "ALL"], params[:per_page].to_i),
         :onchange => "if(this.value){window.location='?per_page='+this.value;}" %></div>
  <%= will_paginate @uktweets %>
</div>

<%= link_to 'Download CSV list', tweets_path(format: :csv), class: "btn" %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/raw.csv.erb
<%- headers = ['Original Tweet', 'Twitter name', 'Full name', 'Bio', 'Location'] -%>
<%= CSV.generate_line headers %>
<%- @csvtweets.each do |tweet| -%>
  <%= CSV.generate_line([tweet.tweeturl, tweet.handle, tweet.name, tweet.bio, tweet.userlocation]) %>
  <% tweet.update_attribute(:downloaded, 'Y') %>
<%- end -%>

app/views/tweets/raw.html.erb
<p id="notice"><%= notice %></p>

<h1>All users who use hubs.ly</h1>

<table>
  <thead>
    <tr>
      <th>Original Tweet</th>
      <th>Twitter handle</th>
      <th>Full name</th>
      <th>Bio</th>
      <th>Location</th>
      <th>UK Based?</th>
      <th>EU Based?</th>
      <th>US Based?</th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
        <tr>
          <td><a href="<%= tweet.tweeturl %>" target="_blank">Original Tweet</a></td>
          <td><a href="http://twitter.com/<%= tweet.handle %>" target="_blank"><%= tweet.handle %></a></td>
          <td><%= tweet.name %></td>
          <td><%= tweet.bio %></td>
          <td><%= tweet.userlocation %></td>
          <td><%= tweet.uk %></td>
          <td><%= tweet.eu %></td>
          <td><%= tweet.us %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="pagination">
<div id="pages">
  How many users per page: <%= select_tag :iper_page, options_for_select([10,20,50, 100, "ALL"], params[:per_page].to_i),
         :onchange => "if(this.value){window.location='?per_page='+this.value;}" %></div>
  <%= will_paginate @tweets %>
</div>
<%= link_to 'Download CSV list', tweets_path(format: :csv), class: "btn" %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeturl:</strong>
  <%= @tweet.tweeturl %>
</p>

<p>
  <strong>Handle:</strong>
  <%= @tweet.handle %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tweet.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @tweet.bio %>
</p>

<p>
  <strong>Userlocation:</strong>
  <%= @tweet.userlocation %>
</p>

<p>
  <strong>Country:</strong>
  <%= @tweet.country %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/us.csv.erb
<%- headers = ['Original Tweet', 'Twitter name', 'Full name', 'Bio', 'Location'] -%>
<%= CSV.generate_line headers %>
<%- @csvtweets.each do |tweet| -%>
  <%= CSV.generate_line([tweet.tweeturl, tweet.handle, tweet.name, tweet.bio, tweet.userlocation]) %>
  <% tweet.update_attribute(:downloaded, 'Y') %>
<%- end -%>

app/views/tweets/us.html.erb
<p id="notice"><%= notice %></p>

<h1>US users who use hubs.ly</h1>

<table>
  <thead>
    <tr>
      <th>Original Tweet</th>
      <th>Twitter handle</th>
      <th>Full name</th>
      <th>Bio</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @ustweets.each do |tweet| %>
        <tr>
          <td><a href="<%= tweet.tweeturl %>" target="_blank">Original Tweet</a></td>
          <td><a href="http://twitter.com/<%= tweet.handle %>" target="_blank"><%= tweet.handle %></a></td>
          <td><%= tweet.name %></td>
          <td><%= tweet.bio %></td>
          <td><%= tweet.userlocation %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="pagination">
<div id="pages">
  How many users per page: <%= select_tag :iper_page, options_for_select([10,20,50, 100, "ALL"], params[:per_page].to_i),
         :onchange => "if(this.value){window.location='?per_page='+this.value;}" %></div>
  <%= will_paginate @ustweets %>
</div>
<%= link_to 'Download CSV list', tweets_path(format: :csv), class: "btn" %>